server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jieshu
    username: root
    password: root
    
    mail:  
    host: smtp.163.com  
    username: jack_husx@163.com  
    password: hushuangxi1990
    properties:  
          mail:  
              smtp:  
              auth: true  
              starttls:  
              enable: true  
              required: true 
              
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  aop:
    auto: true

  http:
    encoding:
      force: true
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB    
mybatis:
  type-aliases-package: cn.tarena.book.pojo
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml



    





